#!/bin/bash
set -e

echo "=== Terrain Intelligence Generator - Native Toolkit Mesh Demo ==="
echo ""
echo "This demo shows how to use the vicar-native-toolkit for native-looking"
echo "VICAR commands that transparently execute inside Docker."
echo ""

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_DIR="$SCRIPT_DIR/vicar-native-toolkit"
WORKSPACE="$TOOLKIT_DIR/workspace"
IMAGE="ghcr.io/nasa-ammos/tig/terrain-intelligence-generator:opensource"

# Parse arguments
STEREO_LEFT=""
STEREO_RIGHT=""
XYZ_FILE=""
TEXTURE_FILE=""

print_usage() {
  echo "Usage: $0 [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  --xyz FILE           Use pre-computed XYZ point cloud (fast)"
  echo "  --stereo-left FILE   Left stereo image (for XYZ calculation)"
  echo "  --stereo-right FILE  Right stereo image (for XYZ calculation)"
  echo "  --texture FILE       Texture image (optional, defaults to left stereo)"
  echo ""
  echo "Examples:"
  echo "  # Use pre-computed XYZ (fast, ~90 seconds)"
  echo "  $0 --xyz pointcloud.IMG --texture image.IMG"
  echo ""
  echo "  # Calculate XYZ from stereo pair (slow, ~10+ minutes)"
  echo "  $0 --stereo-left left.VIC --stereo-right right.VIC"
  echo ""
  echo "Requirements:"
  echo "  - direnv installed and configured"
  echo "  - MARS calibration files available"
  echo "  - Stereo images must be from same acquisition (matching SCLK)"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --xyz)
      XYZ_FILE="$2"
      shift 2
      ;;
    --stereo-left)
      STEREO_LEFT="$2"
      shift 2
      ;;
    --stereo-right)
      STEREO_RIGHT="$2"
      shift 2
      ;;
    --texture)
      TEXTURE_FILE="$2"
      shift 2
      ;;
    --help|-h)
      print_usage
      ;;
    *)
      echo "ERROR: Unknown option: $1"
      print_usage
      ;;
  esac
done

# Validate inputs
if [ -z "$XYZ_FILE" ] && [ -z "$STEREO_LEFT" ]; then
  echo "ERROR: Must specify either --xyz or --stereo-left/--stereo-right"
  print_usage
fi

if [ -n "$STEREO_LEFT" ] && [ -z "$STEREO_RIGHT" ]; then
  echo "ERROR: --stereo-right required when using --stereo-left"
  exit 1
fi

if [ -n "$STEREO_RIGHT" ] && [ -z "$STEREO_LEFT" ]; then
  echo "ERROR: --stereo-left required when using --stereo-right"
  exit 1
fi

# Check prerequisites
echo "Checking prerequisites..."
echo ""

# Check direnv
if ! command -v direnv &> /dev/null; then
  echo "ERROR: direnv not installed"
  echo ""
  echo "Install direnv:"
  echo "  Ubuntu/Debian: sudo apt install direnv"
  echo "  macOS:         brew install direnv"
  echo "  Fedora:        sudo dnf install direnv"
  echo ""
  echo "Then add to shell profile:"
  echo "  bash:  echo 'eval \"\$(direnv hook bash)\"' >> ~/.bashrc"
  echo "  zsh:   echo 'eval \"\$(direnv hook zsh)\"' >> ~/.zshrc"
  exit 1
fi

# Check Docker
if ! command -v docker &> /dev/null; then
  echo "ERROR: docker not installed"
  exit 1
fi

# Check toolkit directory
if [ ! -d "$TOOLKIT_DIR" ]; then
  echo "ERROR: vicar-native-toolkit not found at: $TOOLKIT_DIR"
  exit 1
fi

echo "✓ Prerequisites met"
echo ""

# Configure MARS calibration if available
if [ -f "$SCRIPT_DIR/find-calibration.sh" ]; then
    source "$SCRIPT_DIR/find-calibration.sh"
    CALIB_DIR=$(find_calibration)
    if [ $? -eq 0 ] && verify_calibration "$CALIB_DIR"; then
        # Create config for toolkit with java-vicario image
        cat > "$TOOLKIT_DIR/.envrc.local" << EOF
# Auto-generated by demo-mesh-native-toolkit.sh
export MARS_CONFIG_PATH="$CALIB_DIR"
export CONTAINER_IMAGE="$IMAGE"
EOF
        echo "✓ MARS calibration configured: $CALIB_DIR"
    else
        echo "⚠ WARNING: MARS calibration not found (required for stereo processing)"
        if [ -n "$STEREO_LEFT" ]; then
            echo "ERROR: Cannot process stereo pair without calibration"
            print_calibration_help
            exit 1
        fi
    fi
else
    echo "⚠ WARNING: find-calibration.sh not found"
fi

# Ensure workspace exists
mkdir -p "$WORKSPACE"

# Resolve input file paths to absolute paths before changing directory
if [ -n "$XYZ_FILE" ]; then
  XYZ_FILE="$(cd "$(dirname "$XYZ_FILE")" && pwd)/$(basename "$XYZ_FILE")"
fi
if [ -n "$TEXTURE_FILE" ]; then
  TEXTURE_FILE="$(cd "$(dirname "$TEXTURE_FILE")" && pwd)/$(basename "$TEXTURE_FILE")"
fi
if [ -n "$STEREO_LEFT" ]; then
  STEREO_LEFT="$(cd "$(dirname "$STEREO_LEFT")" && pwd)/$(basename "$STEREO_LEFT")"
fi
if [ -n "$STEREO_RIGHT" ]; then
  STEREO_RIGHT="$(cd "$(dirname "$STEREO_RIGHT")" && pwd)/$(basename "$STEREO_RIGHT")"
fi

# Step 0: Activate toolkit
echo ""
echo "Step 0: Activating VICAR Native Toolkit..."
echo "  This starts the vicar-sidecar container and generates command wrappers"
echo ""

cd "$TOOLKIT_DIR"

# Load direnv environment
# Note: If direnv is blocked, the stderr will contain "is blocked" message
DIRENV_STDERR=$(mktemp)
DIRENV_OUTPUT=$(direnv export bash 2>"$DIRENV_STDERR")

if grep -q "is blocked" "$DIRENV_STDERR"; then
  echo "⚠ direnv not allowed for this directory"
  echo ""
  echo "Run this command to trust the toolkit directory:"
  echo "  cd $TOOLKIT_DIR && direnv allow"
  echo ""
  echo "Then re-run this demo script."
  rm -f "$DIRENV_STDERR"
  exit 1
fi

# Show direnv messages to user
cat "$DIRENV_STDERR"
rm -f "$DIRENV_STDERR"

# Apply direnv environment
eval "$DIRENV_OUTPUT"

echo "✓ Toolkit activated"
echo ""

# Verify toolkit commands available
if ! command -v marsmesh &> /dev/null; then
  echo "ERROR: VICAR commands not found in PATH"
  echo "This usually means the toolkit activation failed"
  exit 1
fi

echo "Available VICAR commands:"
echo "  marsmesh, marsxyz, marscorr, marscor3, marsrfilt, vicario, gen, label, ..."
echo ""

# Copy input files to workspace
cd workspace

if [ -n "$XYZ_FILE" ]; then
  # Use pre-computed XYZ
  echo "Step 1: Copying pre-computed XYZ point cloud..."
  cp "$XYZ_FILE" pointcloud.xyz
  echo "✓ XYZ copied: $(du -h pointcloud.xyz | cut -f1)"
  
  # Set texture
  if [ -n "$TEXTURE_FILE" ]; then
    cp "$TEXTURE_FILE" texture.img
  elif [ -n "$STEREO_LEFT" ]; then
    cp "$STEREO_LEFT" texture.img
  else
    echo "ERROR: No texture specified"
    exit 1
  fi
  
  # For XYZ-only mode, use unfiltered as filtered (no rover to filter)
  cp pointcloud.xyz pointcloud_filtered.xyz
else
  # Calculate XYZ from stereo pair
  echo "Step 1: Processing stereo pair to generate XYZ..."
  echo "  WARNING: This takes 10+ minutes for full-resolution images"
  echo ""
  
  # Validate files exist
  if [ ! -f "$STEREO_LEFT" ]; then
    echo "ERROR: Left stereo file not found: $STEREO_LEFT"
    exit 1
  fi
  if [ ! -f "$STEREO_RIGHT" ]; then
    echo "ERROR: Right stereo file not found: $STEREO_RIGHT"
    exit 1
  fi
  
  # Copy stereo pair to workspace
  cp "$STEREO_LEFT" left.vic
  cp "$STEREO_RIGHT" right.vic
  echo "  ✓ Stereo pair copied"
  
  # Step 1a: Stereo correlation (disparity map)
  echo ""
  echo "  Step 1a: Running stereo correlation..."
  echo "  Note: Commands look native but execute in Docker container!"
  echo ""
  
  echo "    Running initial correlation (marscorr)..."
  marscorr \( left.vic right.vic \) disparity_init.img template=15 search=51 quality=0.2 2>&1 | \
    grep -E "tiepoints gathered|Seed point" | tail -3 || true
  
  if [ ! -f disparity_init.img ]; then
    echo "  ❌ ERROR: marscorr failed to generate disparity_init.img"
    exit 1
  fi
  echo "    ✓ Initial disparity generated"
  
  echo "    Running refinement (marscor3)..."
  marscor3 \( left.vic right.vic \) disparity.img in_disp=disparity_init.img template=11 search=31 quality=0.4 -omp_on 2>&1 | \
    grep -E "tiepoints|Pyramid|Zooming" | tail -3 || true
  
  if [ ! -f disparity.img ]; then
    echo "  ❌ ERROR: marscor3 failed to generate disparity.img"
    exit 1
  fi
  
  echo "  ✓ Disparity map generated"
  
  # Step 1b: Generate XYZ from disparity
  echo ""
  echo "  Step 1b: Generating XYZ point cloud (marsxyz)..."
  marsxyz \( left.vic right.vic \) pointcloud.xyz disp=disparity.img \
    error=10.0 abserr=0.15 lined=100 avgline=50 zlimit=\(-300,300\) spike_range=0.04 outlier=0.5 2>&1 | \
    grep -E "Successfully|valid|rejected|XYZ" | tail -10 || true
  
  if [ ! -f pointcloud.xyz ]; then
    echo "  ❌ ERROR: marsxyz failed to generate pointcloud.xyz"
    exit 1
  fi
  
  echo "  ✓ XYZ point cloud generated"
  
  # Step 1c: Filter rover hardware from XYZ
  echo ""
  echo "  Step 1c: Filtering rover hardware (marsrfilt)..."
  marsrfilt inp=pointcloud.xyz out=pointcloud_filtered.xyz 2>&1 | \
    grep -E "MARSRFILT|Version|Filtering|points|removed" || true
  
  if [ ! -f pointcloud_filtered.xyz ]; then
    echo "  ⚠ WARNING: marsrfilt failed, using unfiltered XYZ"
    cp pointcloud.xyz pointcloud_filtered.xyz
  else
    echo "  ✓ Rover hardware filtered"
  fi
  
  # Use right image as texture
  if [ -n "$TEXTURE_FILE" ]; then
    cp "$TEXTURE_FILE" texture.img
  else
    cp "$STEREO_RIGHT" texture.img
  fi
fi

echo ""
echo "Step 2: Generating 3D mesh (marsmesh)..."
echo "  Command executes in Docker but looks like a native binary!"
echo ""

marsmesh inp=pointcloud_filtered.xyz out=terrain.obj in_skin=texture.img \
  x_subsample=1 y_subsample=1 \
  range_min=0.2 range_mid=100 range_max=100 \
  lod_levels=10 max_angle=87.5 \
  res_min=3000 res_max=500000 density=1 -adaptive \
  maxgap=5 2>&1 | \
  grep -E "MARSMESH|Version|mesh|triangles|vertices|Writing|LOD|decimat" || true

if [ ! -f terrain.obj ]; then
  echo "❌ ERROR: marsmesh failed to generate terrain.obj"
  exit 1
fi

echo "✓ Mesh generated: terrain.obj"
echo ""

# Convert texture using vicario wrapper
echo "Step 3: Converting texture to PNG (vicario)..."
# Note: vicario may show Java warnings but successfully produces output
vicario texture.img texture.png 2>&1 | grep -E "Image write Done|JConvertIIO|inp =|out =|format =|oform =|rescale ="
if [ -f texture.png ]; then
  echo "✓ Texture converted: texture.png"
else
  echo "⚠ Texture conversion failed"
  echo "  Using original texture.img instead"
fi
echo ""

# List results
echo "Step 4: Results summary"
if [ -f texture.png ]; then
  ls -lh pointcloud_filtered.xyz terrain.obj terrain.mtl texture.png 2>/dev/null
else
  ls -lh pointcloud_filtered.xyz terrain.obj terrain.mtl texture.img 2>/dev/null
fi
echo ""

echo "=== Demo Complete ==="
echo ""
echo "Generated files in: $WORKSPACE"
echo "  - pointcloud_filtered.xyz: Filtered point cloud"
echo "  - terrain.obj            : 3D mesh (Wavefront OBJ)"
echo "  - terrain.mtl            : Material file"
if [ -f texture.png ]; then
  echo "  - texture.png            : Texture image"
else
  echo "  - texture.img            : Texture image (VICAR format)"
fi
echo ""
echo "Key advantages of vicar-native-toolkit:"
echo "  ✓ Commands look native: 'marsmesh ...' instead of 'docker exec ...'"
echo "  ✓ Persistent container: No startup/cleanup overhead"
echo "  ✓ Auto-discovery: All 200+ VICAR commands available"
echo "  ✓ Transparent paths: Works from current directory"
echo ""
echo "To view the mesh:"
echo "  - Blender: File → Import → Wavefront (.obj)"
echo "  - MeshLab: File → Import Mesh → terrain.obj"
echo "  - CloudCompare: File → Open → terrain.obj"
echo "  - Online: Upload to https://3dviewer.net/"
echo ""
echo "Toolkit commands:"
echo "  toolkit-status      : Show container status"
echo "  toolkit-shell       : Open bash shell in container"
echo "  toolkit-verify-calib: Check MARS calibration"
echo "  toolkit-stop        : Stop and remove container"
echo ""
echo "The vicar-sidecar container remains running for future use."
echo "To stop it: cd $TOOLKIT_DIR && toolkit-stop"
